on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[ deprecated ]]; then
            echo "::warning::Deprecated function found"
            fi
      - name: set API key
        run: echo "API_KEY=12341213" >> $GITHUB_ENV # to use it again in another steps
      - name: print API
        run: echo "API KEY is $API_KEY"
      - name: Check if file exists
        run: |
          if [[ -f filename.yaml ]]; then 
          echo "::debug::filename exist"
          else
          echo "::error::filename doent exist"
          fi
