on:
  workflow_dispatch:
   inputs:
      environment:
        description: "Choose Environment"
        default: "staging"
        required: true
        type: choice
        options:
          - dev
          - production
          - staging

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: "echo job ${{ github.job }}"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: job2
        run: "echo ${{ github.job }}"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: job3
        run: "echo ${{ github.job }}"
  job_4:
    runs-on: ubuntu-latest
    needs:
      - job_2
      - job_3
    steps:
      - name: job4
        run: "echo ${{ github.job }}"
  job_5:
    runs-on: ubuntu-latest
    needs:
      - job_1
      - job_2
      - job_3
      - job_4
    steps:
      - name: Print ENV name
        run: echo "Environment name is ${{ inputs.environment }}"
        # or
        # run: |
            #npm install / install / build
            ###
            ###
        # working-directory: ./any dir you wanna run this command in 
        # shell: its default with runner or pwsh/python/cmd/powershell or any language scripts then {0} it will be by default for this jobs
            
