on:
  repository_dispatch:
    types:
      - incident_report
jobs:
  handelig_incident:
    runs-on: ubuntu-latest
    steps:
      - name: pirnt incident report
        run: echo "Incident Reported"
